/*
Yandex launches a new business unit - Yandex.Bar. When developing the menu, it became necessary to draw layered cocktails. To support the concept of an IT bar, the decision was made to draw cocktails using ASCII art. You need to read the shape of the glass and the list of ingredients for the layered cocktail, fill the glass with the ingredients in the correct order, and print the result.
Depth of Market description is a symbolic field from 
n lines by m
characters in each. The field consists of characters . (dots), \ (backslashes), / (forward slashes), | (vertical bars), _ (underscores), and spaces.

The bottom of the glass is located on the last n-th line and consists of symbols _ (underscores), located contiguously.

The edges of the glass are drawn to the left and right of the bottom. A face is a "broken line" of characters \ (backslashes), / (forward slashes), | (vertical bars). Each face consists of exactly n characters, starts at the last n
th line and ends in the first. For any pair of adjacent lines i and i+1
face symbols are located in one or adjacent columns. The edges do not intersect and do not touch each other either side or corner. In particular, this implies that in any line except the last
n
th, there is an empty space indicated by spaces.

The background of the glass image consists of symbols . (points) located to the left of the left side of the glass and to the right of the right.

Input format 
The first line contains two numbers n and m (2 <= n <= 100, 3 <= m <= 100), which indicates the size of the field - the order book image.
The following n lines by m symbols in each contain a description of the order book in the format specified above.
The next line contains a number k(0 <= k <= min(n-1, eightnine)) - the number of cocktail ingredients.
The following k lines contain descriptions of ingredients, one on each line. The description looks like name[i], count[i], symbol[i]..
name[i] is  the name i-th ingredient (a string of lowercase Latin letters with a length of at least 1 and no more 10).
counti Is the number of layers 
ith ingredient.
symboli Is the symbol that i-th ingredient must be represented in the image (any character with an ASCII code greater than 32 and less 127, except for those used in the description of the glass image).

output format
V n lines by m characters in each, print the description of the order book in the above format.

Sample Input 1
8 15
\             /
.|           |.
.|           |.
..\         /..
...|       |...
...|       |...
....\     /....
.....\___/.....
2
gin 2 %
tonic 4 *

Sample Output 1
\             /
.|***********|.
.|***********|.
..\********* /..
...|*******|...
...|%%%%%%%|...
....\%%%%%/....
.....\___/.....


Sample Input 2

10 23
.........\   /.........
........./   \.........
......../     \........
......./       \.......
....../         \......
...../           \.....
..../             \....
.../               \...
../                 \..
./___________________\.
1
acid 5 X

Sample Output 2
.........\   /.........
........./   \.........
......../     \........
......./       \.......
....../XXXXXXXXX\......
...../XXXXXXXXXXX\.....
..../XXXXXXXXXXXXX\....
.../XXXXXXXXXXXXXXX\...
../XXXXXXXXXXXXXXXXX\..
./___________________\.


Sample Input 3
16 28
...|                    |...
...|                    |...
...|                    |...
...|                    |...
...|                    |...
...|                    |...
....|                  |....
....|                  |....
....|                  |....
....|                  |....
....|                  |....
.....|                |.....
.....|                |.....
.....|                |.....
.....|                |.....
......|______________|......
4
kahlua 4 k
baileys 5 b
cointreau 3 c
fire 1 !

Sample output 3

...|                    |...
...|                    |...
...|!!!!!!!!!!!!!!!!!!!!|...
...|cccccccccccccccccccc|...
...|cccccccccccccccccccc|...
...|cccccccccccccccccccc|...
....|bbbbbbbbbbbbbbbbbb|....
....|bbbbbbbbbbbbbbbbbb|....
....|bbbbbbbbbbbbbbbbbb|....
....|bbbbbbbbbbbbbbbbbb|....
....|bbbbbbbbbbbbbbbbbb|....
.....|kkkkkkkkkkkkkkkk|.....
.....|kkkkkkkkkkkkkkkk|.....
.....|kkkkkkkkkkkkkkkk|.....
.....|kkkkkkkkkkkkkkkk|.....
......|______________|......


Sample input 4

10 16
...|     \......
...|      /.....
../        /....
...\        /...
....|        \..
...../      |...
......\     /...
.......|   |....
....../     \...
.......\_____\..
4
some 1 (
thing 2 ?
really 3 )
strange 1 ^


Sample Output 4

...|     \......
...|      /.....
../^^^^^^^^/....
...\))))))))/...
....|))))))))\..
...../))))))|...
......\?????/...
.......|???|....
....../(((((\...
.......\_____\..


*/

#include<iostream>
#include<algorithm>
#include<vector>

using namespace std;

int main(){
    freopen("input.txt", "r", stdin);
    freopen("output.txt", "w", stdout);
    int n, m;
    cin >> n >> m;
    vector<string> s(n);
    for(int i = 0; i < n; i++){
        getline(cin >> ws, s[i]);
    }
    int k;
    cin >> k;
    vector<pair<int, char> > ing(k);
    string temp;
    for(int i = 0; i < k; i++){
        cin >> temp >> ing[i].first >> ing[i].second;
    }
    int level = n-2;
    int v = 0;
    for(int hulala = 0; hulala < k; hulala++){
        while(ing[hulala].first--){
            v = 0;
            while(s[level][v] != ' ') v++;
            int spaces = count(s[level].begin(), s[level].end(), ' ');
            while(spaces--){
                s[level][v++] = ing[hulala].second;
            }
            level--;
        }
    }
    for(int i = 0; i < n; i++){
        cout << s[i] << "\n";
    }
    return 0;
}
